# .bash_profile

# Get global aliases and functions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
unset USERNAME

umask 002
